In [1]:
#3x4 random 
import numpy as np
a=np.random.random([3,4])
print(a)

[[0.48007706 0.92846938 0.85044685 0.34100149]
 [0.31514184 0.99612591 0.20292531 0.5036319 ]
 [0.72432481 0.14627121 0.44689359 0.11141679]]


In [2]:
#3x3 zeros
a=np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#shape size datatype
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Dimesnsion:",a.ndim)
print("shape:",a.shape)
print("Datatype:",a.dtype)

Dimesnsion: 2
shape: (3, 3)
Datatype: int64


In [6]:
#flatten
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=a.flatten()
print(b)

[10 20 30 40 50 60 70 80 90]


In [7]:
#arrange
a=np.arange(5,30,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
